### ISSUE TITLE
get_yfull_tree.py not working

### ISSUE THREAD

**Issue by teepean** [freeseek/getftdna#2]
Hello!

I am not sure if this still works but tried it anyway and ran into an error.

`Traceback (most recent call last):
  File "./get_yfull_tree.py", line 56, in <module>
    text = re.findall(r'<div><ul id="tree" class="tree">.*?</div>', r.text, re.DOTALL | re.MULTILINE)[0]
IndexError: list index out of range`

**Comment by freeseek** [comment]
Ah sorry, it has been a long time since I have updated this project. It is likely than FamilyTreeDNA has changed interface and now new code to access their interfaces is needed. :-(

**Comment by teepean** [comment]
Ok, makes sense!
